### PR TITLE
upgrade celery to 4.2.2

### PR DESCRIPTION
**Pull request by awais786**
https://openedx.atlassian.net/browse/BOM-1999
Upgrade celery to 4.2.2
Using edx-celery-utils hash instead of releasing it.
upgrade redis redis==3.1.0   

@jmbowman instead of releasing the edx-celery-utils I am using hash. That packages is in use at several places and releasing is risky.

**NOTE: Before merging this branch deploy this [PR](https://github.com/edx/enterprise-catalog/pull/170/files) on prod**

### CODE REVIEW

**Comment by awais786** [comment]
**I have to update redis to 3.1.0  otherwise it throws following error.**

**celery -A enterprise_catalog worker --loglevel=info**

```
/usr/local/lib/python3.5/dist-packages/jwt/utils.py:8: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release ofcryptography. Please upgrade your Python.
  from cryptography.hazmat.primitives.asymmetric.utils import (
/usr/local/lib/python3.5/dist-packages/celery/platforms.py:796: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/celery/__main__.py", line 16, in main
    _main()
  File "/usr/local/lib/python3.5/dist-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python3.5/dist-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python3.5/dist-packages/celery/bin/base.py", line 275, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python3.5/dist-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/usr/local/lib/python3.5/dist-packages/celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/local/lib/python3.5/dist-packages/celery/bin/worker.py", line 223, in run_from_argv
    return self(*args, **options)
  File "/usr/local/lib/python3.5/dist-packages/celery/bin/base.py", line 238, in __call__
    ret = self.run(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/celery/bin/worker.py", line 257, in run
    **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/worker.py", line 101, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/worker.py", line 124, in setup_instance
    self.should_use_eventloop() if use_eventloop is None
  File "/usr/local/lib/python3.5/dist-packages/celery/worker/worker.py", line 243, in should_use_eventloop
    self._conninfo.transport.implements.asynchronous and
  File "/usr/local/lib/python3.5/dist-packages/kombu/connection.py", line 865, in transport
    self._transport = self.create_transport()
  File "/usr/local/lib/python3.5/dist-packages/kombu/connection.py", line 592, in create_transport
    return self.get_transport_cls()(client=self)
  File "/usr/local/lib/python3.5/dist-packages/kombu/transport/redis.py", line 1038, in __init__
    self.connection_errors, self.channel_errors = self._get_errors()
  File "/usr/local/lib/python3.5/dist-packages/kombu/transport/redis.py", line 1069, in _get_errors
    return get_redis_error_classes()
  File "/usr/local/lib/python3.5/dist-packages/kombu/transport/redis.py", line 88, in get_redis_error_classes
    exceptions.TimeoutError)),
AttributeError: module 'redis.exceptions' has no attribute 'TimeoutError'
```

File: requirements/base.in [hunk 1]
```diff
@@ -21,10 +21,11 @@ edx-rest-api-client==1.9.2
...
-celery==3.1.26.post2
-redis==2.8
+celery
+redis
 rules
 zipp<2.0
 algoliasearch
 langcodes
-edx-celeryutils
+-e git+https://github.com/edx/edx-celeryutils.git@7ec43c5a9f5611b03d9b64b163a5c76165191162#egg=edx-celeryutils
```
Comment (awais786) [inline requirements/base.in:30]: https://github.com/edx/edx-celeryutils/blob/master/setup.py#L77
Matching package name 
```
packages=[
        'celery_utils',
    ]
```

File: requirements/base.in [hunk 2]
```diff
@@ -21,10 +21,10 @@ edx-rest-api-client==1.9.2
...
-celery==3.1.26.post2
-redis==2.8
+celery
+redis
 rules
 zipp<2.0
 algoliasearch
 langcodes
-edx-celeryutils
+-e git+https://github.com/edx/edx-celeryutils.git@7ec43c5a9f5611b03d9b64b163a5c76165191162#egg=celery_utils   # celery-utils has upgrade celery version and it can break other services
```
Comment (awais786) [inline requirements/base.in]: https://github.com/edx/edx-celeryutils/blob/master/setup.py#L77
Matching package name

packages=[
        'celery_utils',
    ]

**Review by iamsobanjaved — APPROVED** [review]

File: requirements/constraints.txt [hunk 3]
```diff
@@ -18,3 +18,9 @@ social-auth-core<3.3.0
 
 # pinned until https://github.com/datadriventests/ddt/issues/83 is resolved
 ddt<1.4.0
+
+
+celery<4.3     # Python 3.8 isn't officially supported until 4.4 and 4.3 requires redis version 3.2.0 or above.
+
+
+redis<3.2.0    # 4.2.2 is not working with redis 2.8.0
```
Comment (jmbowman) [inline requirements/constraints.txt]: Any reasons not to upgrade this further?  I thought most of the breaking changes were in 3.0.0, and we'll need to go up to at least 3.2.0 for further celery upgrades.

Comment (awais786) [reply requirements/constraints.txt]: I thought when we move celery further i will upgrade it at that time. But let me try to upgrade it.

**Comment by awais786** [comment]
@jmbowman please review it and could you please ask the owners to deploy this [PR](https://github.com/edx/enterprise-catalog/pull/170/files) on prod before this merge.

File: requirements/constraints.txt [hunk 4]
```diff
@@ -18,3 +18,8 @@ social-auth-core<3.3.0
 
 # pinned until https://github.com/datadriventests/ddt/issues/83 is resolved
 ddt<1.4.0
+
+
+celery<4.3     # Python 3.8 isn't officially supported until 4.4 and 4.3 requires redis version 3.2.0 or above.
```
Comment (jmbowman) [inline requirements/constraints.txt]: Maybe this comment needs to be updated, now that redis is upgraded?  Needs to explain why we aren't upgrading to an even higher celery version.

**Review by jmbowman — APPROVED** [review]
Looks good other than that one suggestion.  I'll let you know when the other PR is deployed.

**Comment by jmbowman** [comment]
The broker settings PR has now been deployed to production, this one should now be clear to merge.
